name: Ruby CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  test:
    name: Ruby ${{ matrix.ruby }} - ${{ matrix.rails }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [3.1, 3.2, 3.3]
        rails:
          - rails_7.0
          - rails_7.1
          - rails_7.2
          - rails_edge
    env:
      RAILS_ENV: test
      DISPLAY: ":99.0"
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.rails }}.gemfile

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Set up PhantomJS
      run: |
        mkdir -p travis-phantomjs
        wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
        tar -xvf travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C travis-phantomjs
        echo "$PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64/bin" >> $GITHUB_PATH

    - name: Run tests
      run: bundle exec rspec
      env:
       BUNDLE_GEMFILE: gemfiles/${{ matrix.rails }}.gemfile
